a1.sources = source1
a1.channels = channel1
a1.sinks = sink1

a1.sources.source1.type = TAILDIR
a1.sources.source1.filegroups = f1
a1.sources.source1.filegroups.f1 = /home/bigdata/Desktop/project/app.log
a1.sources.source1.positionFile = /home/bigdata/Desktop/project/taildir_position.json

a1.channels.channel1.type = memory

a1.sinks.sink1.type = hdfs
a1.sinks.sink1.hdfs.path = hdfs://localhost:9000/proj/
a1.sinks.sink1.channel = channel1
a1.sinks.sink1.hdfs.fileType = DataStream
a1.sinks.sink1.hdfs.writeFormat = Text
a1.sinks.sink1.hdfs.batchSize = 100
a1.sinks.sink1.hdfs.rollInterval = 10

a1.sources.source1.channels = channel1